services:
  postgres:
    image: postgres:16-alpine
    container_name: webshop-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: webshop-backend
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      PORT: 5000
      DATA_DIR: /app/backend/data


      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

      SECRET_KEY: ${SECRET_KEY}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    ports:
      - "5000:5000"

    volumes:
      - ./backend/data:/app/backend/data

volumes:
  postgres_data: